# Generated by Django 5.2.7 on 2025-10-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
