# Generated by Django 5.2.7 on 2025-10-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='code',
        ),
    ]
