# Generated by Django 5.2.7 on 2025-10-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_todayspecial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todayspecial',
            name='item',
        ),
        migrations.RemoveField(
            model_name='todayspecial',
            name='price',
        ),
        migrations.AddField(
            model_name='todayspecial',
            name='items',
            field=models.ManyToManyField(to='menu.menuitem'),
        ),
    ]
