# Generated by Django 5.2.7 on 2025-10-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_todayspecial_item_remove_todayspecial_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayspecial',
            name='name',
            field=models.CharField(default='Special Menu', max_length=100),
        ),
    ]
