# Generated by Django 5.2.7 on 2025-10-25 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_todayspecial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.todayspecial')),
            ],
        ),
    ]
